version: '3'
services:
  elasticsearch-master:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./master-config:/usr/share/elasticsearch/config
      - ./ik-analyzer:/usr/share/elasticsearch/plugins/ik-analyzer
    

  elasticsearch-slave1:
    image: elasticsearch:latest
    ports:
      - "8200:9200"
      - "8300:9300"
    depends_on:
      - elasticsearch-master
    links:
      - elasticsearch-master
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.ping.unicast.hosts=lasticsearch-master
    volumes:
      - ./slave1-config:/usr/share/elasticsearch/config
      - ./ik-analyzer:/usr/share/elasticsearch/plugins/ik-analyzer

  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - "9100:9100"


  







